### PR TITLE
Too many redirects for GDrive

### PR DESCRIPTION
**Pull request by abelfn**
Not correctly determining file name.

DownloadNavi

DownloadNavi

PureBrowser

PureBrowser

### CODE REVIEW

**Comment by proninyaroslav** [comment]
Do I understand correctly that this commit fixes a 'Too many redirects' of GDrive? And please revert the 'Save and Read offline pages' commit.

**Review by proninyaroslav — CHANGES_REQUESTED** [review]
Revert it

**Comment by abelfn** [comment]
i did revert it but still giving me error

**Comment by proninyaroslav** [comment]
I see no change, you haven't revert the commit.

**Comment by abelfn** [comment]
i am using github desktop

**Comment by proninyaroslav** [comment]
Снимок экрана от 2020-09-03 21-43-52
As you can see, no changes. Maybe you didn't push.

**Comment by abelfn** [comment]
how about now

**Review by proninyaroslav — CHANGES_REQUESTED** [review]
You haven't revert some files
Без названия

**Comment by proninyaroslav** [comment]
Most likely, it will be easier for you to create a new pull request without revert commits.

**Comment by proninyaroslav** [comment]
Please make a new pull request only with HttpConnection

**Pull request closed without merging**
