### PR TITLE
Save and Read offline pages

### PR DESCRIPTION
**Pull request by abelfn**
For the location of the mht file being saved you can change it based on DownloadNavi Save Downloads in storage setting.

For net::ERR_UNKNOWN_URL_SCHEME i have the code but in my case i am not using ViewModel so cant start activity from viewmodel anyway it is simple you can do sth about it.

In my case inside WebViewClient

        `@Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
           
                if (url.startsWith("http")) {  
                   
                   
                    view.loadUrl(url);
                
                } else if (url.startsWith("mailto:")) {  // Load the email address in an external email program.
                    // Use `ACTION_SENDTO` instead of `ACTION_SEND` so that only email programs are launched.
                    Intent emailIntent = new Intent(Intent.ACTION_SENDTO);

                    // Parse the url and set it as the data for the intent.
                    emailIntent.setData(Uri.parse(url));

                    // Open the email program in a new task instead of as part of Browser.
                    emailIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

                    // Make it so.
                    startActivity(emailIntent);

                    // Returning true indicates Browser is handling the URL by creating an intent.
                    return true;
                } else if (url.startsWith("tel:")) {  // Load the phone number in the dialer.
                    // Open the dialer and load the phone number, but wait for the user to place the call.
                    Intent dialIntent = new Intent(Intent.ACTION_DIAL);

                    // Add the phone number to the intent.
                    dialIntent.setData(Uri.parse(url));

                    // Open the dialer in a new task instead of as part of Browser.
                    dialIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

                    // Make it so.
                    startActivity(dialIntent);

                    // Returning true indicates Browser is handling the URL by creating an intent.
                    return true;
                } else {  // Load a system chooser to select an app that can handle the URL.
                    // Open an app that can handle the URL.
                    Intent genericIntent = new Intent(Intent.ACTION_VIEW);

                    // Add the URL to the intent.
                    genericIntent.setData(Uri.parse(url));

                    // List all apps that can handle the URL instead of just opening the first one.
                    genericIntent.addCategory(Intent.CATEGORY_BROWSABLE);

                    // Open the app in a new task instead of as part of Browser.
                    genericIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

                    // Start the app or display a toast if no app is available to handle the URL.
                    try {
                        startActivity(genericIntent);
                    } catch (ActivityNotFoundException exception) {
                       Toast.makeText(getActivity(),"unrecognized url",Toast.LENGTH_LONG).show();
                    }

                    // Returning true indicates Browser is handling the URL by creating an intent.
                    return true;
                }

            }`

### CODE REVIEW

**Comment by proninyaroslav** [comment]
Does it make sense to add the offline pages support? This browser is for downloading files, and offline pages are useless in this case.

**Comment by abelfn** [comment]
as you wish,but why it is failing to build

**Comment by proninyaroslav** [comment]
You forgot to import `Environment`. Build log is available for viewing.
I don't think that it makes sense to add this anyway.

**Comment by abelfn** [comment]
Forget about Save and Read offline pages!

just handle UNKNOWN_URL_SCHEME

this is what i got when i try to click on telegram link from download navi home page

UNKNOWN_URL_SCHEME

this is mine since it is handled it will go to telegram and if telegram app installed it will automatically launch it.,if not it will stay at the telegram page

abelfn

**Comment by proninyaroslav** [comment]
@abelfn 
I don't understand what you mean.

**Comment by abelfn** [comment]
https://stackoverflow.com/questions/41693263/android-webview-err-unknown-url-scheme
https://stackoverflow.com/questions/54811265/unknown-url-scheme

this happens because webview can not open it so you have to handle it if the link you clicked has app installed that can open it the handled url will be opened with the app otherwise return no app can open this link.

**Comment by proninyaroslav** [comment]
Please make a separate issue.

**Pull request closed without merging**
