### PR TITLE
Added a referer header specification option to download dialog

### PR DESCRIPTION
**Pull request by 8176135**
I added another text field after checksum in the add download advanced drop down section, which allows you to specify the referer header for downloads.

Some sites (e.g. pixiv.net) will return a 403 error if you don't have a correct referer header when trying to download their content. This allows you to at least work around that manually by copying and pasting the parent url.

Things to note about this pull request:
- Added 2 lines to the strings.xml, and just copied and pasted that into the translations. I'm not sure how you get the actual translations for them. Also referer being misspelt in the http specifications doesn't help either.
- I used the misspelt "Referer" as the label to match the header that it is adding, though maybe "Referrer" will be clearer.

### CODE REVIEW

**Comment by proninyaroslav** [comment]
Have you already tested this feature?

**Comment by 8176135** [comment]
Yes.

For example, when on my navi branch:
1. Go to https://www.pixiv.net/en/artworks/83953383 on your firefox/chrome android.
2. Long press the image and share with navi
3. navi will complain server returned http 403 error
4. type in the referer https://i.pximg.net/
5. try connect again
6. and it works!
7. press add and it will download fine as well.

**Comment by proninyaroslav** [comment]
Thank you

**Comment by 8176135** [comment]
Oh sorry, I just realized a problem, the copy/clipboard button beside the referer textbox doesn't do anything at the moment. I'm not sure how the checksum one works, I just copied the xml down from the checksum and changed the ID.

**Comment by proninyaroslav** [comment]
@8176135 
I will fix it.

**Comment by abelfn** [comment]
To me, the Added referer header specification option to download dialog is useless.

referer

ifr

As you can see from above images i add referer once now i can download files which requires referer from any website not from this site only.

Also file name ext in download dialog and completed section is not correct but from file explorer ext is jpg which is correct.

**Pull request merged**
